name: LinuxDo Auto Check-in

on:
  schedule:
    # 每天北京时间 8:00 和 20:00 运行 (UTC时间 0:00 和 12:00)
    - cron: '0 0,12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install browser dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Install additional dependencies
        sudo apt-get install -y \
          xvfb \
          libnss3 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxss1 \
          libgconf-2-4 \
          libxrandr2 \
          libasound2 \
          libpangocairo-1.0-0 \
          libatk1.0-0 \
          libcairo-gobject2 \
          libgtk-3-0 \
          libgdk-pixbuf2.0-0 || true
    
    - name: Run LinuxDo check-in
      env:
        LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
        LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
        HEADLESS: true
        BROWSE_ENABLED: true
        CHROME_BIN: /usr/bin/google-chrome-stable
        DISPLAY: :99
        GITHUB_ACTIONS: true
      run: |
        # Start virtual display
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        
        # Run the script
        python main_optimized.py
    
    - name: Upload logs (if needed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: |
          *.png
          *.html
          *.log
